[profile.default]
solc = "0.8.30"
solc_version = "0.8.30"
src = 'src'
optimizer_runs = 44444444
via_ir = true
ffi = true
fs_permissions = [{ access = "read", path = "./script" }]
verbosity = 3
evm_version = "cancun"
gas_limit = "300000000"
bytecode_hash = "none"
out = 'out'
test = 'test/'
cache_path = 'cache/foundry'
auto_detect_solc = true

libs = ["lib"]

remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/',
    '@openzeppelin/=lib/openzeppelin-contracts/contracts/',
]

rpc_endpoints = { sepolia = "${SEPOLIA_RPC_URL}" }
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[profile.default.fuzz]
runs = 1000
seed = "0x4444"

[profile.pr.fuzz]
runs = 10000

[profile.ci.fuzz]
runs = 100000

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz.runs = 100
